apiVersion: apps/v1
kind: Deployment
metadata:
  name: rapheebeauty-dev
  namespace: dev-namespace
  labels:
    app: rapheebeauty-dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: rapheebeauty-dev
  template:
    metadata:
      labels:
        app: rapheebeauty-dev
    spec:
      containers:
        - name: rapheebeauty-dev
          image: blesseddocker/ifeoma-rapheebeauty:dev
          ports:
            - containerPort: 8000
          resources:
            limits:
              memory: "1000Mi"
              cpu: "500m"
            requests:
              memory: "500Mi"
              cpu: "250m"
